services:
  - type: web
    name: discord-music-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
